---

- name: install the python3 packages
  sudo: true
  apt:
    name={{ item }}
    state=present
  with_items:
    - python3.4-dev
    - python3-pip

- name: install flask
  sudo: true
  pip:
    name={{ item }}
    executable=pip3
    state=present
  with_items:
    - Flask
