# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

# how much ram the virtual machine should have
# export $PAD_MEMORY to override the default
PAD_MEMORY = ENV['PAD_MEMORY'] ||= '1024'

IP_ADDRESS = {
  :pad_dev => '192.168.251.77'
}

BOX_SOURCE = 'http://cloud-images.ubuntu.com/'
BOX_TYPE = 'vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
ANSIBLE_PLAYBOOK = '../../ansible/playbooks/dev_pad_fullstack.yml'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :pad_dev do |pad|
    pad.vm.box = 'trusty'
    pad.vm.box_url = BOX_SOURCE + BOX_TYPE
    pad.vm.network "private_network", ip: IP_ADDRESS[:pad_dev]
    # `curl localhost:5000/places` on host will result in connection drop
    # which could be fixed by flask configuration, but that's not a good idea
    # pad.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: false
    pad.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: false
    pad.vm.hostname = "pad-dev"

    # use all available cpu cores
    host = RbConfig::CONFIG['host_os']
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
    elsif host =~ /linux/
      cpus = `nproc`.to_i
    else
      cpus = 1
    end

    pad.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--cpus', cpus]
      vb.customize ['modifyvm', :id, '--memory', PAD_MEMORY]
      vb.customize ['guestproperty', 'set', :id,
                    '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold', 300000]
    end

    pad.vm.synced_folder '../../backend/', '/opt/backend'
    pad.vm.synced_folder '../../frontend/', '/opt/frontend'

    pad.vm.provision 'ansible' do |ansible|
      ansible.inventory_path = 'hosts'
      ansible.playbook = ANSIBLE_PLAYBOOK
      ansible.host_key_checking = false
    end
  end
end
